# Generated by Django 5.2 on 2025-04-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='categories',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
